title = "gitleaks config"

[[rules]]
	id = "Storage.Amazon.AccessKeyID"
	description = "Storage.Amazon.AccessKeyID"
	regex = '''AKI.{5,20}3SQ'''

[[rules]]
	id = "Storage.Amazon.SecretAccessKey"
	description = "Storage.Amazon.SecretAccessKey"
	regex = '''TzX.{5,100}NXl'''
