name: .Net Build UriHelper

on:
  push:
    paths: 
      - 'src/UriHelper/**'
  pull_request:
    paths: 
      - 'src/UriHelper/**'
  workflow_dispatch:
  
jobs:
  build:

    defaults: 
      run:
        working-directory: src/UriHelper
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100

    - name: Test
      run: dotnet test UriHelper.Tests/UriHelper.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

    - name: Build
      run: dotnet build --configuration Release 

    - name: Upload UriHelper
      uses: actions/upload-artifact@v4
      with:
        name: UriHelper
        path: src/UriHelper/UriHelper/bin/Release/*.nupkg

